version: "3.5"


services:
    toran:
        build: .
        image: thanhsmind/toranproxy:latest
        volumes:
            - .:/data
        ports:
            - "80:80"
            - "443:443"
        environment:
            APP_TORAN_HOST: "toranproxy.thanhsmind"
            
